;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG061N2
;;Width: 360
;;Gauge: 15
;;Position: Keep
x-presser-mode auto
x-stitch-number 1
x-speed-number 0
;description: twill fabric
;yarn 'Polyester' is mapped to carrier 4
;basic twill
;bringin carrier with name "4"
;knitting bringin-dummy for carrier 4
x-stitch-number 14
inhook 4
tuck - f58 4
tuck - f56 4
tuck - f54 4
tuck - f52 4
tuck + f53 4
tuck + f55 4
tuck + f57 4
knit - f58 4
knit - f57 4
knit - f56 4
knit - f55 4
knit - f54 4
knit - f53 4
knit - f52 4
releasehook 4
;bringin done
;knitting cast on with carrier 4
x-stitch-number 2
tuck - f50 4
tuck - f48 4
tuck - f46 4
tuck - f44 4
tuck - f42 4
tuck - f40 4
tuck - f38 4
tuck - f36 4
tuck - f34 4
tuck - f32 4
tuck - f30 4
tuck - f28 4
tuck - f26 4
tuck - f24 4
tuck - f22 4
tuck - f20 4
tuck - f18 4
tuck - f16 4
tuck - f14 4
tuck - f12 4
tuck - f10 4
tuck - f8 4
tuck - f6 4
tuck - f4 4
tuck - f2 4
tuck + f1 4
tuck + f3 4
tuck + f5 4
tuck + f7 4
tuck + f9 4
tuck + f11 4
tuck + f13 4
tuck + f15 4
tuck + f17 4
tuck + f19 4
tuck + f21 4
tuck + f23 4
tuck + f25 4
tuck + f27 4
tuck + f29 4
tuck + f31 4
tuck + f33 4
tuck + f35 4
tuck + f37 4
tuck + f39 4
tuck + f41 4
tuck + f43 4
tuck + f45 4
tuck + f47 4
tuck + f49 4
;dropping bringin of carrier 4 needles 52 -> 58
drop f52
drop f53
drop f54
drop f55
drop f56
drop f57
drop f58
x-stitch-number 14
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
knit - f50 4
miss - f49 4
knit - f48 4
miss - f47 4
knit - f46 4
miss - f45 4
knit - f44 4
miss - f43 4
knit - f42 4
miss - f41 4
knit - f40 4
miss - f39 4
knit - f38 4
miss - f37 4
knit - f36 4
miss - f35 4
knit - f34 4
miss - f33 4
knit - f32 4
miss - f31 4
knit - f30 4
miss - f29 4
knit - f28 4
miss - f27 4
knit - f26 4
miss - f25 4
knit - f24 4
miss - f23 4
knit - f22 4
miss - f21 4
knit - f20 4
miss - f19 4
knit - f18 4
miss - f17 4
knit - f16 4
miss - f15 4
knit - f14 4
miss - f13 4
knit - f12 4
miss - f11 4
knit - f10 4
miss - f9 4
knit - f8 4
miss - f7 4
knit - f6 4
miss - f5 4
knit - f4 4
miss - f3 4
knit - f2 4
miss - f1 4
knit + f1 4
miss + f2 4
knit + f3 4
miss + f4 4
knit + f5 4
miss + f6 4
knit + f7 4
miss + f8 4
knit + f9 4
miss + f10 4
knit + f11 4
miss + f12 4
knit + f13 4
miss + f14 4
knit + f15 4
miss + f16 4
knit + f17 4
miss + f18 4
knit + f19 4
miss + f20 4
knit + f21 4
miss + f22 4
knit + f23 4
miss + f24 4
knit + f25 4
miss + f26 4
knit + f27 4
miss + f28 4
knit + f29 4
miss + f30 4
knit + f31 4
miss + f32 4
knit + f33 4
miss + f34 4
knit + f35 4
miss + f36 4
knit + f37 4
miss + f38 4
knit + f39 4
miss + f40 4
knit + f41 4
miss + f42 4
knit + f43 4
miss + f44 4
knit + f45 4
miss + f46 4
knit + f47 4
miss + f48 4
knit + f49 4
miss + f50 4
;cast off
x-stitch-number 3
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b26 f26
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
xfer b31 f31
xfer b32 f32
xfer b33 f33
xfer b34 f34
xfer b35 f35
xfer b36 f36
xfer b37 f37
xfer b38 f38
xfer b39 f39
xfer b40 f40
xfer b41 f41
xfer b42 f42
xfer b43 f43
xfer b44 f44
xfer b45 f45
xfer b46 f46
xfer b47 f47
xfer b48 f48
xfer b49 f49
xfer b50 f50
knit - f50 4
knit - f49 4
knit - f48 4
knit - f47 4
knit - f46 4
knit - f45 4
knit - f44 4
knit - f43 4
knit - f42 4
knit - f41 4
knit - f40 4
knit - f39 4
knit - f38 4
knit - f37 4
knit - f36 4
knit - f35 4
knit - f34 4
knit - f33 4
knit - f32 4
knit - f31 4
knit - f30 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit + f1 4
knit + f1 4
miss + f2 4
xfer f1 b1
rack 1
xfer b1 f2
rack 0
knit - f2 4
xfer f2 b2
rack 1
xfer b2 f3
rack 0
knit + f3 4
miss + f4 4
xfer f3 b3
rack 1
xfer b3 f4
rack 0
knit - f4 4
xfer f4 b4
rack 1
xfer b4 f5
rack 0
knit + f5 4
miss + f6 4
xfer f5 b5
rack 1
xfer b5 f6
rack 0
knit - f6 4
xfer f6 b6
rack 1
xfer b6 f7
rack 0
knit + f7 4
miss + f8 4
xfer f7 b7
rack 1
xfer b7 f8
rack 0
knit - f8 4
xfer f8 b8
rack 1
xfer b8 f9
rack 0
knit + f9 4
miss + f10 4
xfer f9 b9
rack 1
xfer b9 f10
rack 0
knit - f10 4
xfer f10 b10
rack 1
xfer b10 f11
rack 0
knit + f11 4
miss + f12 4
xfer f11 b11
rack 1
xfer b11 f12
rack 0
knit - f12 4
xfer f12 b12
rack 1
xfer b12 f13
rack 0
knit + f13 4
miss + f14 4
xfer f13 b13
rack 1
xfer b13 f14
rack 0
knit - f14 4
xfer f14 b14
rack 1
xfer b14 f15
rack 0
knit + f15 4
miss + f16 4
xfer f15 b15
rack 1
xfer b15 f16
rack 0
knit - f16 4
xfer f16 b16
rack 1
xfer b16 f17
rack 0
knit + f17 4
miss + f18 4
xfer f17 b17
rack 1
xfer b17 f18
rack 0
knit - f18 4
xfer f18 b18
rack 1
xfer b18 f19
rack 0
knit + f19 4
miss + f20 4
xfer f19 b19
rack 1
xfer b19 f20
rack 0
knit - f20 4
xfer f20 b20
rack 1
xfer b20 f21
rack 0
knit + f21 4
miss + f22 4
xfer f21 b21
rack 1
xfer b21 f22
rack 0
knit - f22 4
xfer f22 b22
rack 1
xfer b22 f23
rack 0
knit + f23 4
miss + f24 4
xfer f23 b23
rack 1
xfer b23 f24
rack 0
knit - f24 4
xfer f24 b24
rack 1
xfer b24 f25
rack 0
knit + f25 4
miss + f26 4
xfer f25 b25
rack 1
xfer b25 f26
rack 0
knit - f26 4
xfer f26 b26
rack 1
xfer b26 f27
rack 0
knit + f27 4
miss + f28 4
xfer f27 b27
rack 1
xfer b27 f28
rack 0
knit - f28 4
xfer f28 b28
rack 1
xfer b28 f29
rack 0
knit + f29 4
miss + f30 4
xfer f29 b29
rack 1
xfer b29 f30
rack 0
knit - f30 4
xfer f30 b30
rack 1
xfer b30 f31
rack 0
knit + f31 4
miss + f32 4
xfer f31 b31
rack 1
xfer b31 f32
rack 0
knit - f32 4
xfer f32 b32
rack 1
xfer b32 f33
rack 0
knit + f33 4
miss + f34 4
xfer f33 b33
rack 1
xfer b33 f34
rack 0
knit - f34 4
xfer f34 b34
rack 1
xfer b34 f35
rack 0
knit + f35 4
miss + f36 4
xfer f35 b35
rack 1
xfer b35 f36
rack 0
knit - f36 4
xfer f36 b36
rack 1
xfer b36 f37
rack 0
knit + f37 4
miss + f38 4
xfer f37 b37
rack 1
xfer b37 f38
rack 0
knit - f38 4
xfer f38 b38
rack 1
xfer b38 f39
rack 0
knit + f39 4
miss + f40 4
xfer f39 b39
rack 1
xfer b39 f40
rack 0
knit - f40 4
xfer f40 b40
rack 1
xfer b40 f41
rack 0
knit + f41 4
miss + f42 4
xfer f41 b41
rack 1
xfer b41 f42
rack 0
knit - f42 4
xfer f42 b42
rack 1
xfer b42 f43
rack 0
knit + f43 4
miss + f44 4
xfer f43 b43
rack 1
xfer b43 f44
rack 0
knit - f44 4
xfer f44 b44
rack 1
xfer b44 f45
rack 0
knit + f45 4
miss + f46 4
xfer f45 b45
rack 1
xfer b45 f46
rack 0
knit - f46 4
xfer f46 b46
rack 1
xfer b46 f47
rack 0
knit + f47 4
miss + f48 4
xfer f47 b47
rack 1
xfer b47 f48
rack 0
knit - f48 4
xfer f48 b48
rack 1
xfer b48 f49
rack 0
knit + f49 4
miss + f50 4
xfer f49 b49
rack 1
xfer b49 f50
rack 0
knit - f50 4
xfer f50 b50
rack 1
xfer b50 f51
knit + f51 4
knit - f51 4
knit - f51 4
knit - f51 4
knit - f51 4
knit - f51 4
;racking to 0 for outhook
rack 0
outhook 4
rack 1
drop f51
rack 0
rack 0.25
;6 empty carrier movements
knit - b58 
knit - f58 
knit - b57 
knit - f57 
knit - b56 
knit - f56 
knit - b55 
knit - f55 
knit - b54 
knit - f54 
knit - b53 
knit - f53 
knit - b52 
knit - f52 
knit - b51 
knit - f51 
knit - b50 
knit - f50 
knit - b49 
knit - f49 
knit - b48 
knit - f48 
knit - b47 
knit - f47 
knit - b46 
knit - f46 
knit - b45 
knit - f45 
knit - b44 
knit - f44 
knit - b43 
knit - f43 
knit - b42 
knit - f42 
knit - b41 
knit - f41 
knit - b40 
knit - f40 
knit - b39 
knit - f39 
knit - b38 
knit - f38 
knit - b37 
knit - f37 
knit - b36 
knit - f36 
knit - b35 
knit - f35 
knit - b34 
knit - f34 
knit - b33 
knit - f33 
knit - b32 
knit - f32 
knit - b31 
knit - f31 
knit - b30 
knit - f30 
knit - b29 
knit - f29 
knit - b28 
knit - f28 
knit - b27 
knit - f27 
knit - b26 
knit - f26 
knit - b25 
knit - f25 
knit - b24 
knit - f24 
knit - b23 
knit - f23 
knit - b22 
knit - f22 
knit - b21 
knit - f21 
knit - b20 
knit - f20 
knit - b19 
knit - f19 
knit - b18 
knit - f18 
knit - b17 
knit - f17 
knit - b16 
knit - f16 
knit - b15 
knit - f15 
knit - b14 
knit - f14 
knit - b13 
knit - f13 
knit - b12 
knit - f12 
knit - b11 
knit - f11 
knit - b10 
knit - f10 
knit - b9 
knit - f9 
knit - b8 
knit - f8 
knit - b7 
knit - f7 
knit - b6 
knit - f6 
knit - b5 
knit - f5 
knit - b4 
knit - f4 
knit - b3 
knit - f3 
knit - b2 
knit - f2 
knit - b1 
knit - f1 
knit + f1 
knit + b1 
knit + f2 
knit + b2 
knit + f3 
knit + b3 
knit + f4 
knit + b4 
knit + f5 
knit + b5 
knit + f6 
knit + b6 
knit + f7 
knit + b7 
knit + f8 
knit + b8 
knit + f9 
knit + b9 
knit + f10 
knit + b10 
knit + f11 
knit + b11 
knit + f12 
knit + b12 
knit + f13 
knit + b13 
knit + f14 
knit + b14 
knit + f15 
knit + b15 
knit + f16 
knit + b16 
knit + f17 
knit + b17 
knit + f18 
knit + b18 
knit + f19 
knit + b19 
knit + f20 
knit + b20 
knit + f21 
knit + b21 
knit + f22 
knit + b22 
knit + f23 
knit + b23 
knit + f24 
knit + b24 
knit + f25 
knit + b25 
knit + f26 
knit + b26 
knit + f27 
knit + b27 
knit + f28 
knit + b28 
knit + f29 
knit + b29 
knit + f30 
knit + b30 
knit + f31 
knit + b31 
knit + f32 
knit + b32 
knit + f33 
knit + b33 
knit + f34 
knit + b34 
knit + f35 
knit + b35 
knit + f36 
knit + b36 
knit + f37 
knit + b37 
knit + f38 
knit + b38 
knit + f39 
knit + b39 
knit + f40 
knit + b40 
knit + f41 
knit + b41 
knit + f42 
knit + b42 
knit + f43 
knit + b43 
knit + f44 
knit + b44 
knit + f45 
knit + b45 
knit + f46 
knit + b46 
knit + f47 
knit + b47 
knit + f48 
knit + b48 
knit + f49 
knit + b49 
knit + f50 
knit + b50 
knit + f51 
knit + b51 
knit + f52 
knit + b52 
knit + f53 
knit + b53 
knit + f54 
knit + b54 
knit + f55 
knit + b55 
knit + f56 
knit + b56 
knit + f57 
knit + b57 
knit + f58 
knit + b58 
knit - b58 
knit - f58 
knit - b57 
knit - f57 
knit - b56 
knit - f56 
knit - b55 
knit - f55 
knit - b54 
knit - f54 
knit - b53 
knit - f53 
knit - b52 
knit - f52 
knit - b51 
knit - f51 
knit - b50 
knit - f50 
knit - b49 
knit - f49 
knit - b48 
knit - f48 
knit - b47 
knit - f47 
knit - b46 
knit - f46 
knit - b45 
knit - f45 
knit - b44 
knit - f44 
knit - b43 
knit - f43 
knit - b42 
knit - f42 
knit - b41 
knit - f41 
knit - b40 
knit - f40 
knit - b39 
knit - f39 
knit - b38 
knit - f38 
knit - b37 
knit - f37 
knit - b36 
knit - f36 
knit - b35 
knit - f35 
knit - b34 
knit - f34 
knit - b33 
knit - f33 
knit - b32 
knit - f32 
knit - b31 
knit - f31 
knit - b30 
knit - f30 
knit - b29 
knit - f29 
knit - b28 
knit - f28 
knit - b27 
knit - f27 
knit - b26 
knit - f26 
knit - b25 
knit - f25 
knit - b24 
knit - f24 
knit - b23 
knit - f23 
knit - b22 
knit - f22 
knit - b21 
knit - f21 
knit - b20 
knit - f20 
knit - b19 
knit - f19 
knit - b18 
knit - f18 
knit - b17 
knit - f17 
knit - b16 
knit - f16 
knit - b15 
knit - f15 
knit - b14 
knit - f14 
knit - b13 
knit - f13 
knit - b12 
knit - f12 
knit - b11 
knit - f11 
knit - b10 
knit - f10 
knit - b9 
knit - f9 
knit - b8 
knit - f8 
knit - b7 
knit - f7 
knit - b6 
knit - f6 
knit - b5 
knit - f5 
knit - b4 
knit - f4 
knit - b3 
knit - f3 
knit - b2 
knit - f2 
knit - b1 
knit - f1 
knit + f1 
knit + b1 
knit + f2 
knit + b2 
knit + f3 
knit + b3 
knit + f4 
knit + b4 
knit + f5 
knit + b5 
knit + f6 
knit + b6 
knit + f7 
knit + b7 
knit + f8 
knit + b8 
knit + f9 
knit + b9 
knit + f10 
knit + b10 
knit + f11 
knit + b11 
knit + f12 
knit + b12 
knit + f13 
knit + b13 
knit + f14 
knit + b14 
knit + f15 
knit + b15 
knit + f16 
knit + b16 
knit + f17 
knit + b17 
knit + f18 
knit + b18 
knit + f19 
knit + b19 
knit + f20 
knit + b20 
knit + f21 
knit + b21 
knit + f22 
knit + b22 
knit + f23 
knit + b23 
knit + f24 
knit + b24 
knit + f25 
knit + b25 
knit + f26 
knit + b26 
knit + f27 
knit + b27 
knit + f28 
knit + b28 
knit + f29 
knit + b29 
knit + f30 
knit + b30 
knit + f31 
knit + b31 
knit + f32 
knit + b32 
knit + f33 
knit + b33 
knit + f34 
knit + b34 
knit + f35 
knit + b35 
knit + f36 
knit + b36 
knit + f37 
knit + b37 
knit + f38 
knit + b38 
knit + f39 
knit + b39 
knit + f40 
knit + b40 
knit + f41 
knit + b41 
knit + f42 
knit + b42 
knit + f43 
knit + b43 
knit + f44 
knit + b44 
knit + f45 
knit + b45 
knit + f46 
knit + b46 
knit + f47 
knit + b47 
knit + f48 
knit + b48 
knit + f49 
knit + b49 
knit + f50 
knit + b50 
knit + f51 
knit + b51 
knit + f52 
knit + b52 
knit + f53 
knit + b53 
knit + f54 
knit + b54 
knit + f55 
knit + b55 
knit + f56 
knit + b56 
knit + f57 
knit + b57 
knit + f58 
knit + b58 
knit - b58 
knit - f58 
knit - b57 
knit - f57 
knit - b56 
knit - f56 
knit - b55 
knit - f55 
knit - b54 
knit - f54 
knit - b53 
knit - f53 
knit - b52 
knit - f52 
knit - b51 
knit - f51 
knit - b50 
knit - f50 
knit - b49 
knit - f49 
knit - b48 
knit - f48 
knit - b47 
knit - f47 
knit - b46 
knit - f46 
knit - b45 
knit - f45 
knit - b44 
knit - f44 
knit - b43 
knit - f43 
knit - b42 
knit - f42 
knit - b41 
knit - f41 
knit - b40 
knit - f40 
knit - b39 
knit - f39 
knit - b38 
knit - f38 
knit - b37 
knit - f37 
knit - b36 
knit - f36 
knit - b35 
knit - f35 
knit - b34 
knit - f34 
knit - b33 
knit - f33 
knit - b32 
knit - f32 
knit - b31 
knit - f31 
knit - b30 
knit - f30 
knit - b29 
knit - f29 
knit - b28 
knit - f28 
knit - b27 
knit - f27 
knit - b26 
knit - f26 
knit - b25 
knit - f25 
knit - b24 
knit - f24 
knit - b23 
knit - f23 
knit - b22 
knit - f22 
knit - b21 
knit - f21 
knit - b20 
knit - f20 
knit - b19 
knit - f19 
knit - b18 
knit - f18 
knit - b17 
knit - f17 
knit - b16 
knit - f16 
knit - b15 
knit - f15 
knit - b14 
knit - f14 
knit - b13 
knit - f13 
knit - b12 
knit - f12 
knit - b11 
knit - f11 
knit - b10 
knit - f10 
knit - b9 
knit - f9 
knit - b8 
knit - f8 
knit - b7 
knit - f7 
knit - b6 
knit - f6 
knit - b5 
knit - f5 
knit - b4 
knit - f4 
knit - b3 
knit - f3 
knit - b2 
knit - f2 
knit - b1 
knit - f1 
knit + f1 
knit + b1 
knit + f2 
knit + b2 
knit + f3 
knit + b3 
knit + f4 
knit + b4 
knit + f5 
knit + b5 
knit + f6 
knit + b6 
knit + f7 
knit + b7 
knit + f8 
knit + b8 
knit + f9 
knit + b9 
knit + f10 
knit + b10 
knit + f11 
knit + b11 
knit + f12 
knit + b12 
knit + f13 
knit + b13 
knit + f14 
knit + b14 
knit + f15 
knit + b15 
knit + f16 
knit + b16 
knit + f17 
knit + b17 
knit + f18 
knit + b18 
knit + f19 
knit + b19 
knit + f20 
knit + b20 
knit + f21 
knit + b21 
knit + f22 
knit + b22 
knit + f23 
knit + b23 
knit + f24 
knit + b24 
knit + f25 
knit + b25 
knit + f26 
knit + b26 
knit + f27 
knit + b27 
knit + f28 
knit + b28 
knit + f29 
knit + b29 
knit + f30 
knit + b30 
knit + f31 
knit + b31 
knit + f32 
knit + b32 
knit + f33 
knit + b33 
knit + f34 
knit + b34 
knit + f35 
knit + b35 
knit + f36 
knit + b36 
knit + f37 
knit + b37 
knit + f38 
knit + b38 
knit + f39 
knit + b39 
knit + f40 
knit + b40 
knit + f41 
knit + b41 
knit + f42 
knit + b42 
knit + f43 
knit + b43 
knit + f44 
knit + b44 
knit + f45 
knit + b45 
knit + f46 
knit + b46 
knit + f47 
knit + b47 
knit + f48 
knit + b48 
knit + f49 
knit + b49 
knit + f50 
knit + b50 
knit + f51 
knit + b51 
knit + f52 
knit + b52 
knit + f53 
knit + b53 
knit + f54 
knit + b54 
knit + f55 
knit + b55 
knit + f56 
knit + b56 
knit + f57 
knit + b57 
knit + f58 
knit + b58 
rack 0
