;!knitout-2
;;Carriers: L1 L2 L3 L4 L5 L6 L7 L8 L9 L10
;;Machine: SWG061N2
;;Width: 360
;;Gauge: 15
;;Position: Keep
;description: intarsia in single jersey
;generated 11/02/2022 @ 08:00:08 by P40479 on HAGNB138
;yarn 'Polyester0' is mapped to carrier L3
;yarn 'Polyester1' is mapped to carrier L4
;lower margin area
;bringing in carrier with name "L3"
in L3
tuck + b1 L3
tuck + b6 L3
tuck + b11 L3
tuck + b16 L3
tuck + b21 L3
tuck + b26 L3
tuck + b31 L3
tuck + b36 L3
tuck + b41 L3
tuck + b46 L3
;bringin done
;knitting cast on with carrier L3
knit + f51 L3
knit + b52 L3
knit + f53 L3
knit + b54 L3
knit + f55 L3
knit + b56 L3
knit + f57 L3
knit + b58 L3
knit + f59 L3
knit + b60 L3
knit + f61 L3
knit + b62 L3
knit + f63 L3
knit + b64 L3
knit + f65 L3
knit + b66 L3
knit + f67 L3
knit + b68 L3
knit + f69 L3
knit + b70 L3
knit + f71 L3
knit + b72 L3
knit + f73 L3
knit + b74 L3
knit + f75 L3
knit + b76 L3
knit + f77 L3
knit + b78 L3
knit + f79 L3
knit + b80 L3
knit + f81 L3
knit + b82 L3
knit + f83 L3
knit + b84 L3
knit + f85 L3
knit + b86 L3
knit + f87 L3
knit + b88 L3
knit + f89 L3
knit + b90 L3
knit + f91 L3
knit + b92 L3
knit + f93 L3
knit + b94 L3
knit + f95 L3
knit + b96 L3
knit + f97 L3
knit + b98 L3
knit + f99 L3
knit + b100 L3
knit - f100 L3
knit - b99 L3
knit - f98 L3
knit - b97 L3
knit - f96 L3
knit - b95 L3
knit - f94 L3
knit - b93 L3
knit - f92 L3
knit - b91 L3
knit - f90 L3
knit - b89 L3
knit - f88 L3
knit - b87 L3
knit - f86 L3
knit - b85 L3
knit - f84 L3
knit - b83 L3
knit - f82 L3
knit - b81 L3
knit - f80 L3
knit - b79 L3
knit - f78 L3
knit - b77 L3
knit - f76 L3
knit - b75 L3
knit - f74 L3
knit - b73 L3
knit - f72 L3
knit - b71 L3
knit - f70 L3
knit - b69 L3
knit - f68 L3
knit - b67 L3
knit - f66 L3
knit - b65 L3
knit - f64 L3
knit - b63 L3
knit - f62 L3
knit - b61 L3
knit - f60 L3
knit - b59 L3
knit - f58 L3
knit - b57 L3
knit - f56 L3
knit - b55 L3
knit - f54 L3
knit - b53 L3
knit - f52 L3
knit - b51 L3
xfer b51 f51
xfer b52 f52
xfer b53 f53
xfer b54 f54
xfer b55 f55
xfer b56 f56
xfer b57 f57
xfer b58 f58
xfer b59 f59
xfer b60 f60
xfer b61 f61
xfer b62 f62
xfer b63 f63
xfer b64 f64
xfer b65 f65
xfer b66 f66
xfer b67 f67
xfer b68 f68
xfer b69 f69
xfer b70 f70
xfer b71 f71
xfer b72 f72
xfer b73 f73
xfer b74 f74
xfer b75 f75
xfer b76 f76
xfer b77 f77
xfer b78 f78
xfer b79 f79
xfer b80 f80
xfer b81 f81
xfer b82 f82
xfer b83 f83
xfer b84 f84
xfer b85 f85
xfer b86 f86
xfer b87 f87
xfer b88 f88
xfer b89 f89
xfer b90 f90
xfer b91 f91
xfer b92 f92
xfer b93 f93
xfer b94 f94
xfer b95 f95
xfer b96 f96
xfer b97 f97
xfer b98 f98
xfer b99 f99
xfer b100 f100
;knitting castOn done
;dropping fixation of carrier L3 needles 1 -> 50
drop b1
drop b6
drop b11
drop b16
drop b21
drop b26
drop b31
drop b36
drop b41
drop b46
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
;knitting intarsia area
;bringing in carrier with name "L4"
in L4
tuck + b1 L4
tuck + b6 L4
tuck + b11 L4
tuck + b16 L4
tuck + b21 L4
tuck + b26 L4
tuck + b31 L4
tuck + b36 L4
tuck + b41 L4
tuck + b46 L4
;bringin done
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
;dropping fixation of carrier L4 needles 1 -> 50
drop b1
drop b6
drop b11
drop b16
drop b21
drop b26
drop b31
drop b36
drop b41
drop b46
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
tuck - f90 L3
miss - f89 L3
miss - f88 L3
miss - f87 L3
tuck - f86 L3
miss - f85 L3
miss - f84 L3
miss - f83 L3
tuck - f82 L3
miss - f81 L3
miss - f80 L3
miss - f79 L3
tuck - f78 L3
miss - f77 L3
miss - f76 L3
miss - f75 L3
tuck - f74 L3
miss - f73 L3
miss - f72 L3
miss - f71 L3
tuck - f70 L3
miss - f69 L3
miss - f68 L3
miss - f67 L3
tuck - f66 L3
miss - f65 L3
miss - f64 L3
miss - f63 L3
tuck - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
tuck + f61 L3
miss + f62 L3
miss + f63 L3
miss + f64 L3
tuck + f65 L3
miss + f66 L3
miss + f67 L3
miss + f68 L3
tuck + f69 L3
miss + f70 L3
miss + f71 L3
miss + f72 L3
tuck + f73 L3
miss + f74 L3
miss + f75 L3
miss + f76 L3
tuck + f77 L3
miss + f78 L3
miss + f79 L3
miss + f80 L3
tuck + f81 L3
miss + f82 L3
miss + f83 L3
miss + f84 L3
tuck + f85 L3
miss + f86 L3
miss + f87 L3
miss + f88 L3
tuck + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck - f91 L4
knit - f90 L4
knit - f89 L4
knit - f88 L4
knit - f87 L4
knit - f86 L4
knit - f85 L4
knit - f84 L4
knit - f83 L4
knit - f82 L4
knit - f81 L4
knit - f80 L4
knit - f79 L4
knit - f78 L4
knit - f77 L4
knit - f76 L4
knit - f75 L4
knit - f74 L4
knit - f73 L4
knit - f72 L4
knit - f71 L4
knit - f70 L4
knit - f69 L4
knit - f68 L4
knit - f67 L4
knit - f66 L4
knit - f65 L4
knit - f64 L4
knit - f63 L4
knit - f62 L4
knit - f61 L4
tuck - f60 L4
;fixation was skipped for carrier L4, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
miss - f90 L3
miss - f89 L3
tuck - f88 L3
miss - f87 L3
miss - f86 L3
miss - f85 L3
tuck - f84 L3
miss - f83 L3
miss - f82 L3
miss - f81 L3
tuck - f80 L3
miss - f79 L3
miss - f78 L3
miss - f77 L3
tuck - f76 L3
miss - f75 L3
miss - f74 L3
miss - f73 L3
tuck - f72 L3
miss - f71 L3
miss - f70 L3
miss - f69 L3
tuck - f68 L3
miss - f67 L3
miss - f66 L3
miss - f65 L3
tuck - f64 L3
miss - f63 L3
miss - f62 L3
miss - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
tuck + f60 L4
knit + f61 L4
knit + f62 L4
knit + f63 L4
knit + f64 L4
knit + f65 L4
knit + f66 L4
knit + f67 L4
knit + f68 L4
knit + f69 L4
knit + f70 L4
knit + f71 L4
knit + f72 L4
knit + f73 L4
knit + f74 L4
knit + f75 L4
knit + f76 L4
knit + f77 L4
knit + f78 L4
knit + f79 L4
knit + f80 L4
knit + f81 L4
knit + f82 L4
knit + f83 L4
knit + f84 L4
knit + f85 L4
knit + f86 L4
knit + f87 L4
knit + f88 L4
knit + f89 L4
knit + f90 L4
tuck + f91 L4
;fixation was skipped for carrier L4, releasing hook after first course
out L4
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
miss + f61 L3
miss + f62 L3
tuck + f63 L3
miss + f64 L3
miss + f65 L3
miss + f66 L3
tuck + f67 L3
miss + f68 L3
miss + f69 L3
miss + f70 L3
tuck + f71 L3
miss + f72 L3
miss + f73 L3
miss + f74 L3
tuck + f75 L3
miss + f76 L3
miss + f77 L3
miss + f78 L3
tuck + f79 L3
miss + f80 L3
miss + f81 L3
miss + f82 L3
tuck + f83 L3
miss + f84 L3
miss + f85 L3
miss + f86 L3
tuck + f87 L3
miss + f88 L3
miss + f89 L3
miss + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
;upper margin area
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
;fixation was skipped for carrier L3, releasing hook after first course
knit - f100 L3
knit - f99 L3
knit - f98 L3
knit - f97 L3
knit - f96 L3
knit - f95 L3
knit - f94 L3
knit - f93 L3
knit - f92 L3
knit - f91 L3
knit - f90 L3
knit - f89 L3
knit - f88 L3
knit - f87 L3
knit - f86 L3
knit - f85 L3
knit - f84 L3
knit - f83 L3
knit - f82 L3
knit - f81 L3
knit - f80 L3
knit - f79 L3
knit - f78 L3
knit - f77 L3
knit - f76 L3
knit - f75 L3
knit - f74 L3
knit - f73 L3
knit - f72 L3
knit - f71 L3
knit - f70 L3
knit - f69 L3
knit - f68 L3
knit - f67 L3
knit - f66 L3
knit - f65 L3
knit - f64 L3
knit - f63 L3
knit - f62 L3
knit - f61 L3
knit - f60 L3
knit - f59 L3
knit - f58 L3
knit - f57 L3
knit - f56 L3
knit - f55 L3
knit - f54 L3
knit - f53 L3
knit - f52 L3
knit - f51 L3
;fixation was skipped for carrier L3, releasing hook after first course
;cast off
xfer b51 f51
xfer b52 f52
xfer b53 f53
xfer b54 f54
xfer b55 f55
xfer b56 f56
xfer b57 f57
xfer b58 f58
xfer b59 f59
xfer b60 f60
xfer b61 f61
xfer b62 f62
xfer b63 f63
xfer b64 f64
xfer b65 f65
xfer b66 f66
xfer b67 f67
xfer b68 f68
xfer b69 f69
xfer b70 f70
xfer b71 f71
xfer b72 f72
xfer b73 f73
xfer b74 f74
xfer b75 f75
xfer b76 f76
xfer b77 f77
xfer b78 f78
xfer b79 f79
xfer b80 f80
xfer b81 f81
xfer b82 f82
xfer b83 f83
xfer b84 f84
xfer b85 f85
xfer b86 f86
xfer b87 f87
xfer b88 f88
xfer b89 f89
xfer b90 f90
xfer b91 f91
xfer b92 f92
xfer b93 f93
xfer b94 f94
xfer b95 f95
xfer b96 f96
xfer b97 f97
xfer b98 f98
xfer b99 f99
xfer b100 f100
knit + f51 L3
knit + f52 L3
knit + f53 L3
knit + f54 L3
knit + f55 L3
knit + f56 L3
knit + f57 L3
knit + f58 L3
knit + f59 L3
knit + f60 L3
knit + f61 L3
knit + f62 L3
knit + f63 L3
knit + f64 L3
knit + f65 L3
knit + f66 L3
knit + f67 L3
knit + f68 L3
knit + f69 L3
knit + f70 L3
knit + f71 L3
knit + f72 L3
knit + f73 L3
knit + f74 L3
knit + f75 L3
knit + f76 L3
knit + f77 L3
knit + f78 L3
knit + f79 L3
knit + f80 L3
knit + f81 L3
knit + f82 L3
knit + f83 L3
knit + f84 L3
knit + f85 L3
knit + f86 L3
knit + f87 L3
knit + f88 L3
knit + f89 L3
knit + f90 L3
knit + f91 L3
knit + f92 L3
knit + f93 L3
knit + f94 L3
knit + f95 L3
knit + f96 L3
knit + f97 L3
knit + f98 L3
knit + f99 L3
knit + f100 L3
knit - f100 L3
knit + f100 L3
knit - f100 L3
miss - f99 L3
xfer f100 b100
rack -1
xfer b100 f99
rack 0
knit + f99 L3
knit - f99 L3
knit + f99 L3
xfer f99 b99
rack -1
xfer b99 f98
rack 0
knit - f98 L3
knit + f98 L3
knit - f98 L3
miss - f97 L3
xfer f98 b98
rack -1
xfer b98 f97
rack 0
knit + f97 L3
knit - f97 L3
knit + f97 L3
xfer f97 b97
rack -1
xfer b97 f96
rack 0
knit - f96 L3
knit + f96 L3
knit - f96 L3
miss - f95 L3
xfer f96 b96
rack -1
xfer b96 f95
rack 0
knit + f95 L3
knit - f95 L3
knit + f95 L3
xfer f95 b95
rack -1
xfer b95 f94
rack 0
knit - f94 L3
knit + f94 L3
knit - f94 L3
miss - f93 L3
xfer f94 b94
rack -1
xfer b94 f93
rack 0
knit + f93 L3
knit - f93 L3
knit + f93 L3
xfer f93 b93
rack -1
xfer b93 f92
rack 0
knit - f92 L3
knit + f92 L3
knit - f92 L3
miss - f91 L3
xfer f92 b92
rack -1
xfer b92 f91
rack 0
knit + f91 L3
knit - f91 L3
knit + f91 L3
xfer f91 b91
rack -1
xfer b91 f90
rack 0
knit - f90 L3
knit + f90 L3
knit - f90 L3
miss - f89 L3
xfer f90 b90
rack -1
xfer b90 f89
rack 0
knit + f89 L3
knit - f89 L3
knit + f89 L3
xfer f89 b89
rack -1
xfer b89 f88
rack 0
knit - f88 L3
knit + f88 L3
knit - f88 L3
miss - f87 L3
xfer f88 b88
rack -1
xfer b88 f87
rack 0
knit + f87 L3
knit - f87 L3
knit + f87 L3
xfer f87 b87
rack -1
xfer b87 f86
rack 0
knit - f86 L3
knit + f86 L3
knit - f86 L3
miss - f85 L3
xfer f86 b86
rack -1
xfer b86 f85
rack 0
knit + f85 L3
knit - f85 L3
knit + f85 L3
xfer f85 b85
rack -1
xfer b85 f84
rack 0
knit - f84 L3
knit + f84 L3
knit - f84 L3
miss - f83 L3
xfer f84 b84
rack -1
xfer b84 f83
rack 0
knit + f83 L3
knit - f83 L3
knit + f83 L3
xfer f83 b83
rack -1
xfer b83 f82
rack 0
knit - f82 L3
knit + f82 L3
knit - f82 L3
miss - f81 L3
xfer f82 b82
rack -1
xfer b82 f81
rack 0
knit + f81 L3
knit - f81 L3
knit + f81 L3
xfer f81 b81
rack -1
xfer b81 f80
rack 0
knit - f80 L3
knit + f80 L3
knit - f80 L3
miss - f79 L3
xfer f80 b80
rack -1
xfer b80 f79
rack 0
knit + f79 L3
knit - f79 L3
knit + f79 L3
xfer f79 b79
rack -1
xfer b79 f78
rack 0
knit - f78 L3
knit + f78 L3
knit - f78 L3
miss - f77 L3
xfer f78 b78
rack -1
xfer b78 f77
rack 0
knit + f77 L3
knit - f77 L3
knit + f77 L3
xfer f77 b77
rack -1
xfer b77 f76
rack 0
knit - f76 L3
knit + f76 L3
knit - f76 L3
miss - f75 L3
xfer f76 b76
rack -1
xfer b76 f75
rack 0
knit + f75 L3
knit - f75 L3
knit + f75 L3
xfer f75 b75
rack -1
xfer b75 f74
rack 0
knit - f74 L3
knit + f74 L3
knit - f74 L3
miss - f73 L3
xfer f74 b74
rack -1
xfer b74 f73
rack 0
knit + f73 L3
knit - f73 L3
knit + f73 L3
xfer f73 b73
rack -1
xfer b73 f72
rack 0
knit - f72 L3
knit + f72 L3
knit - f72 L3
miss - f71 L3
xfer f72 b72
rack -1
xfer b72 f71
rack 0
knit + f71 L3
knit - f71 L3
knit + f71 L3
xfer f71 b71
rack -1
xfer b71 f70
rack 0
knit - f70 L3
knit + f70 L3
knit - f70 L3
miss - f69 L3
xfer f70 b70
rack -1
xfer b70 f69
rack 0
knit + f69 L3
knit - f69 L3
knit + f69 L3
xfer f69 b69
rack -1
xfer b69 f68
rack 0
knit - f68 L3
knit + f68 L3
knit - f68 L3
miss - f67 L3
xfer f68 b68
rack -1
xfer b68 f67
rack 0
knit + f67 L3
knit - f67 L3
knit + f67 L3
xfer f67 b67
rack -1
xfer b67 f66
rack 0
knit - f66 L3
knit + f66 L3
knit - f66 L3
miss - f65 L3
xfer f66 b66
rack -1
xfer b66 f65
rack 0
knit + f65 L3
knit - f65 L3
knit + f65 L3
xfer f65 b65
rack -1
xfer b65 f64
rack 0
knit - f64 L3
knit + f64 L3
knit - f64 L3
miss - f63 L3
xfer f64 b64
rack -1
xfer b64 f63
rack 0
knit + f63 L3
knit - f63 L3
knit + f63 L3
xfer f63 b63
rack -1
xfer b63 f62
rack 0
knit - f62 L3
knit + f62 L3
knit - f62 L3
miss - f61 L3
xfer f62 b62
rack -1
xfer b62 f61
rack 0
knit + f61 L3
knit - f61 L3
knit + f61 L3
xfer f61 b61
rack -1
xfer b61 f60
rack 0
knit - f60 L3
knit + f60 L3
knit - f60 L3
miss - f59 L3
xfer f60 b60
rack -1
xfer b60 f59
rack 0
knit + f59 L3
knit - f59 L3
knit + f59 L3
xfer f59 b59
rack -1
xfer b59 f58
rack 0
knit - f58 L3
knit + f58 L3
knit - f58 L3
miss - f57 L3
xfer f58 b58
rack -1
xfer b58 f57
rack 0
knit + f57 L3
knit - f57 L3
knit + f57 L3
xfer f57 b57
rack -1
xfer b57 f56
rack 0
knit - f56 L3
knit + f56 L3
knit - f56 L3
miss - f55 L3
xfer f56 b56
rack -1
xfer b56 f55
rack 0
knit + f55 L3
knit - f55 L3
knit + f55 L3
xfer f55 b55
rack -1
xfer b55 f54
rack 0
knit - f54 L3
knit + f54 L3
knit - f54 L3
miss - f53 L3
xfer f54 b54
rack -1
xfer b54 f53
rack 0
knit + f53 L3
knit - f53 L3
knit + f53 L3
xfer f53 b53
rack -1
xfer b53 f52
rack 0
knit - f52 L3
knit + f52 L3
knit - f52 L3
miss - f51 L3
xfer f52 b52
rack -1
xfer b52 f51
rack 0
knit + f51 L3
knit - f51 L3
knit + f51 L3
xfer f51 b51
rack -1
xfer b51 f50
rack 0
knit - f50 L3
knit - f50 L3
knit - f50 L3
knit - f50 L3
knit - f50 L3
out L3
drop f50
rack 0.25
;6 empty carrier movements
knit - b100 
knit - f100 
knit - b99 
knit - f99 
knit - b98 
knit - f98 
knit - b97 
knit - f97 
knit - b96 
knit - f96 
knit - b95 
knit - f95 
knit - b94 
knit - f94 
knit - b93 
knit - f93 
knit - b92 
knit - f92 
knit - b91 
knit - f91 
knit - b90 
knit - f90 
knit - b89 
knit - f89 
knit - b88 
knit - f88 
knit - b87 
knit - f87 
knit - b86 
knit - f86 
knit - b85 
knit - f85 
knit - b84 
knit - f84 
knit - b83 
knit - f83 
knit - b82 
knit - f82 
knit - b81 
knit - f81 
knit - b80 
knit - f80 
knit - b79 
knit - f79 
knit - b78 
knit - f78 
knit - b77 
knit - f77 
knit - b76 
knit - f76 
knit - b75 
knit - f75 
knit - b74 
knit - f74 
knit - b73 
knit - f73 
knit - b72 
knit - f72 
knit - b71 
knit - f71 
knit - b70 
knit - f70 
knit - b69 
knit - f69 
knit - b68 
knit - f68 
knit - b67 
knit - f67 
knit - b66 
knit - f66 
knit - b65 
knit - f65 
knit - b64 
knit - f64 
knit - b63 
knit - f63 
knit - b62 
knit - f62 
knit - b61 
knit - f61 
knit - b60 
knit - f60 
knit - b59 
knit - f59 
knit - b58 
knit - f58 
knit - b57 
knit - f57 
knit - b56 
knit - f56 
knit - b55 
knit - f55 
knit - b54 
knit - f54 
knit - b53 
knit - f53 
knit - b52 
knit - f52 
knit - b51 
knit - f51 
knit - b50 
knit - f50 
knit - b49 
knit - f49 
knit - b48 
knit - f48 
knit - b47 
knit - f47 
knit - b46 
knit - f46 
knit - b45 
knit - f45 
knit - b44 
knit - f44 
knit - b43 
knit - f43 
knit - b42 
knit - f42 
knit - b41 
knit - f41 
knit - b40 
knit - f40 
knit - b39 
knit - f39 
knit - b38 
knit - f38 
knit - b37 
knit - f37 
knit - b36 
knit - f36 
knit - b35 
knit - f35 
knit - b34 
knit - f34 
knit - b33 
knit - f33 
knit - b32 
knit - f32 
knit - b31 
knit - f31 
knit - b30 
knit - f30 
knit - b29 
knit - f29 
knit - b28 
knit - f28 
knit - b27 
knit - f27 
knit - b26 
knit - f26 
knit - b25 
knit - f25 
knit - b24 
knit - f24 
knit - b23 
knit - f23 
knit - b22 
knit - f22 
knit - b21 
knit - f21 
knit - b20 
knit - f20 
knit - b19 
knit - f19 
knit - b18 
knit - f18 
knit - b17 
knit - f17 
knit - b16 
knit - f16 
knit - b15 
knit - f15 
knit - b14 
knit - f14 
knit - b13 
knit - f13 
knit - b12 
knit - f12 
knit - b11 
knit - f11 
knit - b10 
knit - f10 
knit - b9 
knit - f9 
knit - b8 
knit - f8 
knit - b7 
knit - f7 
knit - b6 
knit - f6 
knit - b5 
knit - f5 
knit - b4 
knit - f4 
knit - b3 
knit - f3 
knit - b2 
knit - f2 
knit - b1 
knit - f1 
knit + f1 
knit + b1 
knit + f2 
knit + b2 
knit + f3 
knit + b3 
knit + f4 
knit + b4 
knit + f5 
knit + b5 
knit + f6 
knit + b6 
knit + f7 
knit + b7 
knit + f8 
knit + b8 
knit + f9 
knit + b9 
knit + f10 
knit + b10 
knit + f11 
knit + b11 
knit + f12 
knit + b12 
knit + f13 
knit + b13 
knit + f14 
knit + b14 
knit + f15 
knit + b15 
knit + f16 
knit + b16 
knit + f17 
knit + b17 
knit + f18 
knit + b18 
knit + f19 
knit + b19 
knit + f20 
knit + b20 
knit + f21 
knit + b21 
knit + f22 
knit + b22 
knit + f23 
knit + b23 
knit + f24 
knit + b24 
knit + f25 
knit + b25 
knit + f26 
knit + b26 
knit + f27 
knit + b27 
knit + f28 
knit + b28 
knit + f29 
knit + b29 
knit + f30 
knit + b30 
knit + f31 
knit + b31 
knit + f32 
knit + b32 
knit + f33 
knit + b33 
knit + f34 
knit + b34 
knit + f35 
knit + b35 
knit + f36 
knit + b36 
knit + f37 
knit + b37 
knit + f38 
knit + b38 
knit + f39 
knit + b39 
knit + f40 
knit + b40 
knit + f41 
knit + b41 
knit + f42 
knit + b42 
knit + f43 
knit + b43 
knit + f44 
knit + b44 
knit + f45 
knit + b45 
knit + f46 
knit + b46 
knit + f47 
knit + b47 
knit + f48 
knit + b48 
knit + f49 
knit + b49 
knit + f50 
knit + b50 
knit + f51 
knit + b51 
knit + f52 
knit + b52 
knit + f53 
knit + b53 
knit + f54 
knit + b54 
knit + f55 
knit + b55 
knit + f56 
knit + b56 
knit + f57 
knit + b57 
knit + f58 
knit + b58 
knit + f59 
knit + b59 
knit + f60 
knit + b60 
knit + f61 
knit + b61 
knit + f62 
knit + b62 
knit + f63 
knit + b63 
knit + f64 
knit + b64 
knit + f65 
knit + b65 
knit + f66 
knit + b66 
knit + f67 
knit + b67 
knit + f68 
knit + b68 
knit + f69 
knit + b69 
knit + f70 
knit + b70 
knit + f71 
knit + b71 
knit + f72 
knit + b72 
knit + f73 
knit + b73 
knit + f74 
knit + b74 
knit + f75 
knit + b75 
knit + f76 
knit + b76 
knit + f77 
knit + b77 
knit + f78 
knit + b78 
knit + f79 
knit + b79 
knit + f80 
knit + b80 
knit + f81 
knit + b81 
knit + f82 
knit + b82 
knit + f83 
knit + b83 
knit + f84 
knit + b84 
knit + f85 
knit + b85 
knit + f86 
knit + b86 
knit + f87 
knit + b87 
knit + f88 
knit + b88 
knit + f89 
knit + b89 
knit + f90 
knit + b90 
knit + f91 
knit + b91 
knit + f92 
knit + b92 
knit + f93 
knit + b93 
knit + f94 
knit + b94 
knit + f95 
knit + b95 
knit + f96 
knit + b96 
knit + f97 
knit + b97 
knit + f98 
knit + b98 
knit + f99 
knit + b99 
knit + f100 
knit + b100 
knit - b100 
knit - f100 
knit - b99 
knit - f99 
knit - b98 
knit - f98 
knit - b97 
knit - f97 
knit - b96 
knit - f96 
knit - b95 
knit - f95 
knit - b94 
knit - f94 
knit - b93 
knit - f93 
knit - b92 
knit - f92 
knit - b91 
knit - f91 
knit - b90 
knit - f90 
knit - b89 
knit - f89 
knit - b88 
knit - f88 
knit - b87 
knit - f87 
knit - b86 
knit - f86 
knit - b85 
knit - f85 
knit - b84 
knit - f84 
knit - b83 
knit - f83 
knit - b82 
knit - f82 
knit - b81 
knit - f81 
knit - b80 
knit - f80 
knit - b79 
knit - f79 
knit - b78 
knit - f78 
knit - b77 
knit - f77 
knit - b76 
knit - f76 
knit - b75 
knit - f75 
knit - b74 
knit - f74 
knit - b73 
knit - f73 
knit - b72 
knit - f72 
knit - b71 
knit - f71 
knit - b70 
knit - f70 
knit - b69 
knit - f69 
knit - b68 
knit - f68 
knit - b67 
knit - f67 
knit - b66 
knit - f66 
knit - b65 
knit - f65 
knit - b64 
knit - f64 
knit - b63 
knit - f63 
knit - b62 
knit - f62 
knit - b61 
knit - f61 
knit - b60 
knit - f60 
knit - b59 
knit - f59 
knit - b58 
knit - f58 
knit - b57 
knit - f57 
knit - b56 
knit - f56 
knit - b55 
knit - f55 
knit - b54 
knit - f54 
knit - b53 
knit - f53 
knit - b52 
knit - f52 
knit - b51 
knit - f51 
knit - b50 
knit - f50 
knit - b49 
knit - f49 
knit - b48 
knit - f48 
knit - b47 
knit - f47 
knit - b46 
knit - f46 
knit - b45 
knit - f45 
knit - b44 
knit - f44 
knit - b43 
knit - f43 
knit - b42 
knit - f42 
knit - b41 
knit - f41 
knit - b40 
knit - f40 
knit - b39 
knit - f39 
knit - b38 
knit - f38 
knit - b37 
knit - f37 
knit - b36 
knit - f36 
knit - b35 
knit - f35 
knit - b34 
knit - f34 
knit - b33 
knit - f33 
knit - b32 
knit - f32 
knit - b31 
knit - f31 
knit - b30 
knit - f30 
knit - b29 
knit - f29 
knit - b28 
knit - f28 
knit - b27 
knit - f27 
knit - b26 
knit - f26 
knit - b25 
knit - f25 
knit - b24 
knit - f24 
knit - b23 
knit - f23 
knit - b22 
knit - f22 
knit - b21 
knit - f21 
knit - b20 
knit - f20 
knit - b19 
knit - f19 
knit - b18 
knit - f18 
knit - b17 
knit - f17 
knit - b16 
knit - f16 
knit - b15 
knit - f15 
knit - b14 
knit - f14 
knit - b13 
knit - f13 
knit - b12 
knit - f12 
knit - b11 
knit - f11 
knit - b10 
knit - f10 
knit - b9 
knit - f9 
knit - b8 
knit - f8 
knit - b7 
knit - f7 
knit - b6 
knit - f6 
knit - b5 
knit - f5 
knit - b4 
knit - f4 
knit - b3 
knit - f3 
knit - b2 
knit - f2 
knit - b1 
knit - f1 
knit + f1 
knit + b1 
knit + f2 
knit + b2 
knit + f3 
knit + b3 
knit + f4 
knit + b4 
knit + f5 
knit + b5 
knit + f6 
knit + b6 
knit + f7 
knit + b7 
knit + f8 
knit + b8 
knit + f9 
knit + b9 
knit + f10 
knit + b10 
knit + f11 
knit + b11 
knit + f12 
knit + b12 
knit + f13 
knit + b13 
knit + f14 
knit + b14 
knit + f15 
knit + b15 
knit + f16 
knit + b16 
knit + f17 
knit + b17 
knit + f18 
knit + b18 
knit + f19 
knit + b19 
knit + f20 
knit + b20 
knit + f21 
knit + b21 
knit + f22 
knit + b22 
knit + f23 
knit + b23 
knit + f24 
knit + b24 
knit + f25 
knit + b25 
knit + f26 
knit + b26 
knit + f27 
knit + b27 
knit + f28 
knit + b28 
knit + f29 
knit + b29 
knit + f30 
knit + b30 
knit + f31 
knit + b31 
knit + f32 
knit + b32 
knit + f33 
knit + b33 
knit + f34 
knit + b34 
knit + f35 
knit + b35 
knit + f36 
knit + b36 
knit + f37 
knit + b37 
knit + f38 
knit + b38 
knit + f39 
knit + b39 
knit + f40 
knit + b40 
knit + f41 
knit + b41 
knit + f42 
knit + b42 
knit + f43 
knit + b43 
knit + f44 
knit + b44 
knit + f45 
knit + b45 
knit + f46 
knit + b46 
knit + f47 
knit + b47 
knit + f48 
knit + b48 
knit + f49 
knit + b49 
knit + f50 
knit + b50 
knit + f51 
knit + b51 
knit + f52 
knit + b52 
knit + f53 
knit + b53 
knit + f54 
knit + b54 
knit + f55 
knit + b55 
knit + f56 
knit + b56 
knit + f57 
knit + b57 
knit + f58 
knit + b58 
knit + f59 
knit + b59 
knit + f60 
knit + b60 
knit + f61 
knit + b61 
knit + f62 
knit + b62 
knit + f63 
knit + b63 
knit + f64 
knit + b64 
knit + f65 
knit + b65 
knit + f66 
knit + b66 
knit + f67 
knit + b67 
knit + f68 
knit + b68 
knit + f69 
knit + b69 
knit + f70 
knit + b70 
knit + f71 
knit + b71 
knit + f72 
knit + b72 
knit + f73 
knit + b73 
knit + f74 
knit + b74 
knit + f75 
knit + b75 
knit + f76 
knit + b76 
knit + f77 
knit + b77 
knit + f78 
knit + b78 
knit + f79 
knit + b79 
knit + f80 
knit + b80 
knit + f81 
knit + b81 
knit + f82 
knit + b82 
knit + f83 
knit + b83 
knit + f84 
knit + b84 
knit + f85 
knit + b85 
knit + f86 
knit + b86 
knit + f87 
knit + b87 
knit + f88 
knit + b88 
knit + f89 
knit + b89 
knit + f90 
knit + b90 
knit + f91 
knit + b91 
knit + f92 
knit + b92 
knit + f93 
knit + b93 
knit + f94 
knit + b94 
knit + f95 
knit + b95 
knit + f96 
knit + b96 
knit + f97 
knit + b97 
knit + f98 
knit + b98 
knit + f99 
knit + b99 
knit + f100 
knit + b100 
knit - b100 
knit - f100 
knit - b99 
knit - f99 
knit - b98 
knit - f98 
knit - b97 
knit - f97 
knit - b96 
knit - f96 
knit - b95 
knit - f95 
knit - b94 
knit - f94 
knit - b93 
knit - f93 
knit - b92 
knit - f92 
knit - b91 
knit - f91 
knit - b90 
knit - f90 
knit - b89 
knit - f89 
knit - b88 
knit - f88 
knit - b87 
knit - f87 
knit - b86 
knit - f86 
knit - b85 
knit - f85 
knit - b84 
knit - f84 
knit - b83 
knit - f83 
knit - b82 
knit - f82 
knit - b81 
knit - f81 
knit - b80 
knit - f80 
knit - b79 
knit - f79 
knit - b78 
knit - f78 
knit - b77 
knit - f77 
knit - b76 
knit - f76 
knit - b75 
knit - f75 
knit - b74 
knit - f74 
knit - b73 
knit - f73 
knit - b72 
knit - f72 
knit - b71 
knit - f71 
knit - b70 
knit - f70 
knit - b69 
knit - f69 
knit - b68 
knit - f68 
knit - b67 
knit - f67 
knit - b66 
knit - f66 
knit - b65 
knit - f65 
knit - b64 
knit - f64 
knit - b63 
knit - f63 
knit - b62 
knit - f62 
knit - b61 
knit - f61 
knit - b60 
knit - f60 
knit - b59 
knit - f59 
knit - b58 
knit - f58 
knit - b57 
knit - f57 
knit - b56 
knit - f56 
knit - b55 
knit - f55 
knit - b54 
knit - f54 
knit - b53 
knit - f53 
knit - b52 
knit - f52 
knit - b51 
knit - f51 
knit - b50 
knit - f50 
knit - b49 
knit - f49 
knit - b48 
knit - f48 
knit - b47 
knit - f47 
knit - b46 
knit - f46 
knit - b45 
knit - f45 
knit - b44 
knit - f44 
knit - b43 
knit - f43 
knit - b42 
knit - f42 
knit - b41 
knit - f41 
knit - b40 
knit - f40 
knit - b39 
knit - f39 
knit - b38 
knit - f38 
knit - b37 
knit - f37 
knit - b36 
knit - f36 
knit - b35 
knit - f35 
knit - b34 
knit - f34 
knit - b33 
knit - f33 
knit - b32 
knit - f32 
knit - b31 
knit - f31 
knit - b30 
knit - f30 
knit - b29 
knit - f29 
knit - b28 
knit - f28 
knit - b27 
knit - f27 
knit - b26 
knit - f26 
knit - b25 
knit - f25 
knit - b24 
knit - f24 
knit - b23 
knit - f23 
knit - b22 
knit - f22 
knit - b21 
knit - f21 
knit - b20 
knit - f20 
knit - b19 
knit - f19 
knit - b18 
knit - f18 
knit - b17 
knit - f17 
knit - b16 
knit - f16 
knit - b15 
knit - f15 
knit - b14 
knit - f14 
knit - b13 
knit - f13 
knit - b12 
knit - f12 
knit - b11 
knit - f11 
knit - b10 
knit - f10 
knit - b9 
knit - f9 
knit - b8 
knit - f8 
knit - b7 
knit - f7 
knit - b6 
knit - f6 
knit - b5 
knit - f5 
knit - b4 
knit - f4 
knit - b3 
knit - f3 
knit - b2 
knit - f2 
knit - b1 
knit - f1 
knit + f1 
knit + b1 
knit + f2 
knit + b2 
knit + f3 
knit + b3 
knit + f4 
knit + b4 
knit + f5 
knit + b5 
knit + f6 
knit + b6 
knit + f7 
knit + b7 
knit + f8 
knit + b8 
knit + f9 
knit + b9 
knit + f10 
knit + b10 
knit + f11 
knit + b11 
knit + f12 
knit + b12 
knit + f13 
knit + b13 
knit + f14 
knit + b14 
knit + f15 
knit + b15 
knit + f16 
knit + b16 
knit + f17 
knit + b17 
knit + f18 
knit + b18 
knit + f19 
knit + b19 
knit + f20 
knit + b20 
knit + f21 
knit + b21 
knit + f22 
knit + b22 
knit + f23 
knit + b23 
knit + f24 
knit + b24 
knit + f25 
knit + b25 
knit + f26 
knit + b26 
knit + f27 
knit + b27 
knit + f28 
knit + b28 
knit + f29 
knit + b29 
knit + f30 
knit + b30 
knit + f31 
knit + b31 
knit + f32 
knit + b32 
knit + f33 
knit + b33 
knit + f34 
knit + b34 
knit + f35 
knit + b35 
knit + f36 
knit + b36 
knit + f37 
knit + b37 
knit + f38 
knit + b38 
knit + f39 
knit + b39 
knit + f40 
knit + b40 
knit + f41 
knit + b41 
knit + f42 
knit + b42 
knit + f43 
knit + b43 
knit + f44 
knit + b44 
knit + f45 
knit + b45 
knit + f46 
knit + b46 
knit + f47 
knit + b47 
knit + f48 
knit + b48 
knit + f49 
knit + b49 
knit + f50 
knit + b50 
knit + f51 
knit + b51 
knit + f52 
knit + b52 
knit + f53 
knit + b53 
knit + f54 
knit + b54 
knit + f55 
knit + b55 
knit + f56 
knit + b56 
knit + f57 
knit + b57 
knit + f58 
knit + b58 
knit + f59 
knit + b59 
knit + f60 
knit + b60 
knit + f61 
knit + b61 
knit + f62 
knit + b62 
knit + f63 
knit + b63 
knit + f64 
knit + b64 
knit + f65 
knit + b65 
knit + f66 
knit + b66 
knit + f67 
knit + b67 
knit + f68 
knit + b68 
knit + f69 
knit + b69 
knit + f70 
knit + b70 
knit + f71 
knit + b71 
knit + f72 
knit + b72 
knit + f73 
knit + b73 
knit + f74 
knit + b74 
knit + f75 
knit + b75 
knit + f76 
knit + b76 
knit + f77 
knit + b77 
knit + f78 
knit + b78 
knit + f79 
knit + b79 
knit + f80 
knit + b80 
knit + f81 
knit + b81 
knit + f82 
knit + b82 
knit + f83 
knit + b83 
knit + f84 
knit + b84 
knit + f85 
knit + b85 
knit + f86 
knit + b86 
knit + f87 
knit + b87 
knit + f88 
knit + b88 
knit + f89 
knit + b89 
knit + f90 
knit + b90 
knit + f91 
knit + b91 
knit + f92 
knit + b92 
knit + f93 
knit + b93 
knit + f94 
knit + b94 
knit + f95 
knit + b95 
knit + f96 
knit + b96 
knit + f97 
knit + b97 
knit + f98 
knit + b98 
knit + f99 
knit + b99 
knit + f100 
knit + b100 
rack 0
